libs =
#import libs += libhello%lib{hello}

./: exe{co_curl-examples} doc{README.md} manifest

exe{co_curl-examples}: {hxx ixx txx cxx}{*} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
