libs =
import libs += co_curl%lib{co_curl}

./: doc{README.md} manifest

for example_cpp : cxx{*}
{
    example_name = $name($example_cpp)
    ./ : exe{$example_name}: $example_cpp $libs
}


cxx.poptions =+ "-I$out_root" "-I$src_root"
